export const ApartmentBuildingDetails = [
  {
    fieldId: "buildingId",
    fieldLabel: "Building Id",
    fieldType: "input",
    fieldConfig: {
      type: "text",
      placeholder: "#AB-12345",
      value: "",
      validation: { required: true },
    },
  },
  {
    fieldId: "localAuthorityId",
    fieldLabel: "Local Authority ID",
    fieldType: "input",
    fieldConfig: {
      type: "text",
      placeholder: "LA-98765",
      value: "",
      validation: { required: true },
    },
  },
  {
    fieldId: "contractType",
    fieldLabel: "Contract Type",
    fieldType: "input",
    fieldConfig: {
      type: "text",
      placeholder: "Management",
      value: "",
      validation: { required: true },
    },
  },
  {
    fieldId: "electricityAndWaterRegisteredNumber",
    fieldLabel: "Electricity and Water Registered Number",
    fieldType: "input",
    fieldConfig: {
      type: "text",
      placeholder: "EW-456789",
      value: "",
      validation: { required: true },
    },
  },
  {
    fieldId: "buildingName",
    fieldLabel: "Building Name",
    fieldType: "input",
    fieldConfig: {
      type: "text",
      placeholder: "Sunrise Apartments",
      value: "",
      validation: { required: true },
    },
  },
  {
    fieldId: "country",
    fieldLabel: "Country",
    fieldType: "select",
    fieldConfig: {
      type: "select",
      placeholder: "UAE",
      options: [{ value: "UAE", label: "United Arab Emirates" }],
      value: "",
      validation: { required: true },
    },
  },
  {
    fieldId: "city",
    fieldLabel: "City",
    fieldType: "select",
    fieldConfig: {
      type: "select",
      placeholder: "Dubai",
      options: [{ value: "Dubai", label: "Dubai" }],
      value: "",
      validation: { required: true },
    },
  },
  {
    fieldId: "street",
    fieldLabel: "Street",
    fieldType: "input",
    fieldConfig: {
      type: "text",
      placeholder: "Sheikh Zayed Road",
      value: "",
      validation: { required: true },
    },
  },
  {
    fieldId: "gpsCoordinates",
    fieldLabel: "GPS Coordinates",
    fieldType: "input",
    fieldConfig: {
      type: "text",
      placeholder: "25.2048° N, 55.2708° E",
      value: "",
      validation: { required: true },
    },
  },
  {
    fieldId: "managementContractExpiry",
    fieldLabel: "Management Contract Expiry",
    fieldType: "date",
    fieldConfig: {
      type: "date",
      placeholder: "31/12/2025",
      value: "",
      validation: { required: true },
    },
  },
  {
    fieldId: "numberOfFLoors",
    fieldLabel: "Number of Floors",
    fieldType: "input",
    fieldConfig: {
      type: "text",
      placeholder: "12",
      value: "",
      validation: { required: true },
    },
  },
  {
    fieldId: "numberofApartments",
    fieldLabel: "Number of Apartments",
    fieldType: "input",
    fieldConfig: {
      type: "text",
      placeholder: "48",
      value: "",
      validation: { required: true },
    },
  },
  {
    fieldId: "commercialSpaces",
    fieldLabel: "Commercial Spaces",
    fieldType: "input",
    fieldConfig: {
      type: "text",
      placeholder: "4",
      value: "",
      validation: { required: true },
    },
  },
  {
    fieldId: "numberOfParkingSpaces",
    fieldLabel: "Number of Parking Spaces",
    fieldType: "input",
    fieldConfig: {
      type: "text",
      placeholder: "60",
      value: "",
      validation: { required: true },
    },
  },
  {
    fieldId: "features",
    fieldLabel: "Features",
    fieldType: "checkbox",
    fieldConfig: {
      type: "checkbox",
      options: [
        { value: false, label: "Gym" },
        { value: false, label: "Swimming Pool" },
        { value: false, label: "CCTV" },
        { value: false, label: "Free Wi-fi" },
        { value: false, label: "Air conditioning" },
        { value: false, label: "Security Guard" },
        { value: false, label: "Terrace" },
      ],
    },
  },
];
